require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "spec/rails_helper.rb"
    - "config/initializers/devise.rb"
    - "config/environments/development.rb"
Metrics/BlockLength:
 IgnoredMethods: ["describe", "context", "feature", "scenario", "let", "it", "draw", "configure"]

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
