require:
  - rubocop-rails

AllCops:
 TargetRubyVersion: 2.7.0
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

# Cop de documentação com comentário
Documentation:
 Enabled: false

# Esta é uma Cop polêmica, pois pode ajudar na performance. Isso se tornará
# padrão no Ruby 3, mas deixamos a seu critério. Caso deseje manter esta Cop,
# basta remover estas linhas
Style/FrozenStringLiteralComment:
 Enabled: false

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context']

# caracteres de uma linha
Metrics/LineLength:
  Max: 80

# Fazer comentários usando acentos e caracteres não ascii
AsciiComments:
  Enabled: false